# Generated by Django 5.0.6 on 2024-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
